package com.smartclinic.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SelfRegistrationRequest {
    private String name;
    private Integer age;
    private String gender;
    private String phone;
    private String symptoms;
    private String disease;
    
    // Getters are automatically generated by @Data
}